name: build and deploy (win, linux, mac, web)
on: push

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v10
        with:
          actions-cache-folder: 'emsdk-cache'

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          emcmake cmake -B build -DPLATFORM_SDL2=ON -DGB_SINGLE_FILE=ON -DGB_ENABLE_FORCE_INLINE=OFF -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j2

          # need to cleanup the cmake files
          rm -rf build/src/platforms/sdl2/CMakeFiles
          rm -rf build/src/platforms/sdl2/cmake_install.cmake
          rm -rf build/src/platforms/sdl2/Makefile
          rm -rf build/src/platforms/sdl2/res

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/src/platforms/sdl2 # The folder the action should deploy.

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup vcpkg libs
        run: |
          vcpkg install sdl2:x64-windows sdl2-image:x64-windows zlib:x64-windows nativefiledialog:x64-windows

      - name: Build emu
        run: |
          cmake -B build -DPLATFORM_SDL2=ON -DGB_SINGLE_FILE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
          cmake --build build -j2 --config Release

      - name: Collect files
        run: |
          mkdir upload
          move build\src\platforms\sdl2\Release\*.exe upload
          move build\src\platforms\sdl2\Release\*.dll upload

      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: totalgb-windows
          path: upload

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup vcpkg libs
        run: |
            vcpkg install sdl2 sdl2-image zlib nativefiledialog

      - name: Build emu
        run: |
          cmake -B build -DPLATFORM_SDL2=ON -DGB_SINGLE_FILE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build -j3

      - name: Collect files
        run: |
          mv build/src/platforms/sdl2/TotalGB_SDL2 ./TotalGB_SDL2
          tar -cvf ./TotalGB_SDL2.tar ./TotalGB_SDL2

      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: totalgb-macos
          path: TotalGB_SDL2.tar

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup vcpkg libs
        run: |
          vcpkg install sdl2 sdl2-image zlib nativefiledialog

      - name: Build emu
        run: |
          cmake -B build -DPLATFORM_SDL2=ON -DGB_SINGLE_FILE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build -j2

      - name: Collect files
        run: |
          mv build/src/platforms/sdl2/TotalGB_SDL2 ./TotalGB_SDL2
          tar -cvf TotalGB_SDL2.tar ./TotalGB_SDL2

      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: totalgb-linux
          path: TotalGB_SDL2.tar

  build-libretro-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build emu
        run: |
          cmake -B build -DPLATFORM_LIBRETRO=ON -DGB_SINGLE_FILE=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j2 --config Release

      - name: Collect files
        run: |
          mkdir upload/cores
          mkdir upload/info
          move build\src\platforms\libretro\Release\*.dll upload/cores
          copy src/platforms/libretro/totalgb_libretro.info upload/info

      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: totalgb-libretro-windows
          path: upload

  build-libretro-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build emu
        run: |
          cmake -B build -DPLATFORM_LIBRETRO=ON -DGB_SINGLE_FILE=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j3

      - name: Collect files
        run: |
          mkdir -p upload/cores upload/info
          mv build/src/platforms/libretro/totalgb_libretro* upload/cores
          cp src/platforms/libretro/totalgb_libretro.info upload/info

      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: totalgb-libretro-macos
          path: upload

  build-libretro-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build emu
        run: |
          cmake -B build -DPLATFORM_LIBRETRO=ON -DGB_SINGLE_FILE=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j2

      - name: Collect files
        run: |
          mkdir -p upload/cores upload/info
          mv build/src/platforms/libretro/totalgb_libretro.so upload/cores
          cp src/platforms/libretro/totalgb_libretro.info upload/info

      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: totalgb-libretro-linux
          path: upload
